In [4]:
import numpy as np
print("\nNama : Muhammad Hasbi Sabilulhaq\nNIM : 2107944\nProdi : Pilkom-A 2021\nUniversitas Pendidikan Indonesia\n")
A = np.array([ [1,2,0], [2,2,1], [0,3,3] ])
B = np.array([ [-1,5], [3,1], [0,1] ])
print("Menampilkan Matriks A : ")
A
print("Menampilkan Matriks A : ")
B

print("\nHasil Perjumlahan dan Perkalian Matriks A dan B\n")

print("Hasil Perkalian Matriks A dan B : ")
perkalian_matriks = np.dot(A,B)
print(perkalian_matriks)
print("Hasil Perjumlahan Matriks A dan A : ")
print(A + A)
print("Hasil Perjumlahan Matriks B dan B : ")
print(B + B)


Nama : Muhammad Hasbi Sabilulhaq
NIM : 2107944
Prodi : Pilkom-A 2021
Universitas Pendidikan Indonesia

Menampilkan Matriks A : 
Menampilkan Matriks A : 

Hasil Perjumlahan dan Perkalian Matriks A dan B

Hasil Perkalian Matriks A dan B : 
[[ 5  7]
 [ 4 13]
 [ 9  6]]
Hasil Perjumlahan Matriks A dan A : 
[[2 4 0]
 [4 4 2]
 [0 6 6]]
Hasil Perjumlahan Matriks B dan B : 
[[-2 10]
 [ 6  2]
 [ 0  2]]
